version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=8000
      - HOST=0.0.0.0
    volumes:
      - .:/app
    restart: unless-stopped
